### ISSUE TITLE
Installing packages step is over complicated

### ISSUE THREAD

**Issue by DaemonBeast** [LegendaryEmoji/Norbo#1]
The following step is over complicated:

> - Before You Start You Need To Install These Packages How To Install? [Ignore If You're Repl Or Glitch User] : discord.js, fs, figlet, node-fetch, util

The required packages are stored in the **package.json** dependencies field:

> ```json
>  "dependencies": {
>    "discord.js": "^12.2.0",
>    "figlet": "^1.5.0",
>    "fs": "0.0.1-security",
>    "node-fetch": "^2.6.0",
>    "util": "^0.12.3"
>  }
>```

As a result, all the user needs to do is run the following command in their console:

```shell
npm install
```

This will install all the dependencies listed in the **package.json** at once, instead of the user having to install each package individually.

The step could be changed to something similar to the following:

- Before You Start You Need To Install The Necessary Packages By Executing `npm install` In Your Console/Terminal [Ignore If You're Repl Or Glitch User]

**Comment by LegendaryEmoji** [comment]
Oh Thanks!
